[package]
name = "backend-axum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = { version = "7.0.3", features = ["bson"] }
axum = "0.7.5"
bson = "2.10.0"
dotenv = "0.15.0"
futures = "0.3.30"
once_cell = "1.19.0"
serde = { version="1.0.197", features = ["derive"] }
tokio = "1.37.0"
tower = "0.4.13"
tower-http = { version="0.5.2", features = ["trace"] }
tower-service = "0.3.2"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dependencies.mongodb]
version = "2.8.2"
default-features = false
features = ["async-std-runtime"]
