[site]
title = "子线程 | SubThread"

[gql]
protocol = "http"
host = "127.0.0.1"
port = "8009"
path = "graphql"

[comment]
repo = "ZxcVcx/whynote"
repoid = "R_kgDOLuwgKw"
category = "Announcements"
categoryid = "DIC_kwDOLuwgK84CfMER"
mapping="pathname"
strict="0"
reactionsenabled="1"
emitmetadata="0"
inputposition="top"
theme="preferred_color_scheme"
lang="zh-CN"
loading="lazy"
