# https://github.com/trunk-rs/trunk/blob/main/Trunk.toml

[build]
target = "index.html"
dist = "dist"


[serve]
# The address to serve on LAN.
addresses = ["127.0.0.1"]
# The address to serve on WAN.
# address = "0.0.0.0"
# The port to serve on.
port = 8001

