
on:
  push:
    paths:
      - 'frontend-yew/**'

name: gh-page

permissions:
  contents: write
env:
  # The project name specified in your Cargo.toml
  PROJECT_NAME: whynote
  FRONTEND_NAME: frontend-yew
  PUBLIC_URL: /whynote
jobs:
  deploy:
    # Set the job to run on the platform specified by the matrix below
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
 
      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Install trunk
        uses: baptiste0928/cargo-install@v3
        with:
          crate: trunk
      
      - name: Install wasm-bindgen-cli
        uses: baptiste0928/cargo-install@v3
        with:
          crate: wasm-bindgen-cli

      - name: Install wasm-opt
        uses: baptiste0928/cargo-install@v3
        with:
          crate: wasm-opt

      - name: Build frontend
        working-directory: ./${{ env.FRONTEND_NAME }}
        run: trunk build --release --public-url "${{ env.PUBLIC_URL }}"
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./${{ env.FRONTEND_NAME }}/dist

      - name: Zip dist folder
        run: zip -r ${{ env.FRONTEND_NAME }}.zip ${{ env.FRONTEND_NAME }}/dist

      - name: Upload release file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FRONTEND_NAME }}-dist-${{ github.sha }}
          path: ${{ env.FRONTEND_NAME }}.zip