name: mac-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  stable-aarch64-apple-darwin-build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Upload ARM64
    - uses: actions/upload-artifact@v4
      with:
        name: backend-axum-stable-aarch64-apple-darwin-${{ github.sha }}
        path: /Users/runner/work/whynote/whynote/target/release/backend-axum
